apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
spec:
  selector:
    matchLabels:
      app: custom-app
  replicas: 2
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
      - name: argocd-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
